ASM = nasm

SRC_DIR = src
BUILD_DIR = build

.PHONY: all floppy_image kernel bootloader clean always

# _________________________________________
# FLOPPY IMAGE
# FAT FS Documentation: https://wiki.osdev.org/FAT
floppy_image: $(BUILD_DIR)/main_floppy.img
$(BUILD_DIR)/main_floppy.img: bootloader kernel
	dd if=/dev/zero of=$(BUILD_DIR)/main_floppy.img bs=512 count=2880
  hdiutil attach -nomount $(BUILD_DIR)/main_floppy.img
	newfs_msdos -F 12 -f 2880 -v NBOS disk4
  hdiutil detach disk4
	dd if=$(BUILD_DIR)/bootloader.bin of=$(BUILD_DIR)/main_floppy.img conv=notrunc
	mcopy -i $(BUILD_DIR)/main_floppy.img $(BUILD_DIR)/kernel.bin "::kernel.bin"

	# _________________________________________
	# FLOPPY IMAGE CREATION FROM TUTORIAL TWO:
	# dd if=/dev/zero of=$(BUILD_DIR)/main_floppy.img bs=512 count=2880
	# mkfs.fat -F 12 -n "NBOS" $(BUILD_DIR)/main_floppy.img
	# dd if=$(BUILD_DIR)/bootloader.bin of=$(BUILD_DIR)/main_floppy.img conv=notrunc
	# mcopy -i $(BUILD_DIR)/main_floppy.img $(BUILD_DIR)/kernel.bin "::kernel.bin"

	# _________________________________________
	# FLOPPY IMAGE CREATION FROM TUTORIAL ONE:
	# cp $(BUILD_DIR)/main.bin $(BUILD_DIR)/main_floppy.img
	# truncate -s 1440k $(BUILD_DIR)/main_floppy.img

# _________________________________________
# BOOTLOADER
bootloader: $(BUILD_DIR)/bootloader.bin
$(BUILD_DIR)/bootloader.bin: always
	$(ASM) $(SRC_DIR)/bootloader/boot.asm -f bin -o $(BUILD_DIR)/bootloader.bin

# _________________________________________
# KERNEL
kernel: $(BUILD_DIR)/kernel.bin
$(BUILD_DIR)/kernel.bin: always
	$(ASM) $(SRC_DIR)/kernel/main.asm -f bin -o $(BUILD_DIR)/kernel.bin

# _________________________________________
# ALWAYS
always:
	mkdir -p $(BUILD_DIR)

# _________________________________________
# CLEAN
clean: 
	rm -rf $(BUILD_DIR)/*
